<a href="https://colab.research.google.com/github/parisharmaa/CodSoft/blob/main/spam_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [ ]:
# import data
spam_df = pd.read_csv("/content/spam.csv")

In [ ]:
# inspect data
spam_df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
spam_df.groupby('Category')

In [ ]:
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [ ]:
# turn spam/ham into numerical data , creating a new column called 'spam'
spam_df['spam']= spam_df['Category'].apply ( lambda x: 1 if x =='spam' else 0 )

In [ ]:
spam_df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [ ]:
# create train/test split
x_train , x_test, y_train, y_test = train_test_split (spam_df.Message,spam_df.spam)

In [ ]:
x_train

726     Got it! It looks scrumptious... daddy wants to...
2323                              Should I be stalking u?
4163    How's it going? Got any exciting karaoke type ...
2010    I can't keep going through this. It was never ...
2091             S:-)kallis wont play in first two odi:-)
                              ...                        
4058                      Noice. Text me when you're here
362                                       Oh ok no prob..
1224       Rofl betta invest in some  anti aging products
884                           Dude we should go sup again
552     Hurry up, I've been weed-deficient for like th...
Name: Message, Length: 4179, dtype: object

In [ ]:
x_train.describe()

count                       4179
unique                      3930
top       Sorry, I'll call later
freq                          19
Name: Message, dtype: object

In [ ]:
# find word count and store data as a matrix
cv= CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [ ]:
x_train_count

<4179x7346 sparse matrix of type '<class 'numpy.int64'>'
	with 55003 stored elements in Compressed Sparse Row format>

In [ ]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#train model
model= MultinomialNB()
model.fit( x_train_count,y_train )

MultinomialNB()

In [ ]:
email_ham = ["hey wanna meet up for the game?"]
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0])

In [ ]:
# pre-test spam
email_spam = ["reward money click"]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1])

In [ ]:
# test model
x_test_count = cv.transform(x_test)
model.score (x_test_count,y_test)

0.9877961234745154